[package]
name = "constmatrix"
version = "0.1.0"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2018"

[dependencies]
approx = { version = "0.4.0", optional = true }
cfg-if = "1.0.0"
float = { path = "../float" }
num-traits = "0.2.14"
