[package]
name = "integrate"
version = "0.1.0"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2018"

[dependencies]
float = { path = "../float/" }
rayon = { version = "1.5.0", optional = true }
