[package]
name = "shallow-water"
version = "0.1.0"
authors = ["Magnus Ulimoen <magnus@ulimoen.dev>"]
edition = "2021"

[dependencies]
ndarray = "0.15.4"
sbp = { path = "../sbp" }
log = "0.4.17"
integrate = { path = "../utils/integrate" }
